# ==================== SERVER ====================
server.port=8081

# ==================== DATABASE (SUPABASE - POSTGRESQL) ====================
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ykvitgxpwejmxknzkxpa
spring.datasource.password=Giridhar_130405
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==================== JWT ====================
jwt.secret=VGhpcy1pcy1hLXZlcnktbG9uZy1zZWNyZXQta2V5LXRvLWVuc3VyZS1pdC1pcy1hdC1sZWFzdC0yNTYtYml0cw==
jwt.expiration=86400000

# ==================== EMAIL (Gmail SMTP) ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=girideveloper07@gmail.com
spring.mail.password=unnpysylycjgmbmw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ==================== LOGGING ====================
logging.level.com.hotel=DEBUG
logging.level.org.springframework.security=INFO
# logging.file.name=logs/hotel-app.log

# ==================== ASYNC ====================
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10

# ==================== STRIPE ====================
# REPLACE THE KEYS BELOW WITH YOUR STRIPE TEST KEYS
stripe.secret.key="SampleSecretKeyForTestingPurposesOnly"
stripe.publishable.key="SamplePublishableKeyForTestingPurposesOnly"
stripe.success.url=http://localhost:3000/my-bookings?payment=success&session_id={CHECKOUT_SESSION_ID}
stripe.cancel.url=http://localhost:3000/hotels/%d?payment=cancel